import React, { useState, useEffect } from 'react'
import Nav from '../components/Nav'
import { listInstitutions, listCoursesForInstitution, applyToCourse, listStudentApplications } from '../services/firestore'
import { uploadTranscriptFile } from '../services/storage'
import { useAuth } from '../services/auth'
const SYMBOLS = ['A','B','C','D','E','F']; const SYMBOL_VALUE = {A:5,B:4,C:3,D:2,E:1,F:0}
export default function StudentDashboard(){
  const [institutions,setInstitutions]=useState([]); const [selectedInstitution,setSelectedInstitution]=useState(''); const [courses,setCourses]=useState([]); const [subjects,setSubjects]=useState([]); const [file,setFile]=useState(null); const [progress,setProgress]=useState(0); const [transcriptUrl,setTranscriptUrl]=useState(null); const [applications,setApplications]=useState([])
  const { user, profile } = useAuth()
  useEffect(()=>{ (async ()=>{ const list = await listInstitutions(); setInstitutions(list.filter(i=>i.approved)); if(list.length>0) setSelectedInstitution(list.find(i=>i.approved).id); if(user){ const apps = await listStudentApplications(user.uid); setApplications(apps);} })() },[user])
  useEffect(()=>{ (async ()=>{ if(selectedInstitution){ const cs = await listCoursesForInstitution(selectedInstitution); setCourses(cs) } else setCourses([]) })() },[selectedInstitution])
  function addSubject(){ setSubjects(s=>[...s,{subject:'Mathematics',symbol:'C'}]) }
  function updateSubject(i,key,val){ setSubjects(s=>{ const copy=[...s]; copy[i]={...copy[i],[key]:val}; return copy }) }
  async function doUpload(){ if(!file) return alert('select pdf'); if(!user) return alert('signin'); try{ const r = await uploadTranscriptFile(file,user.uid,(p)=> setProgress(p)); setTranscriptUrl(r.url); alert('uploaded') }catch(e){ alert('upload failed '+e.message) } }
  function matches(course){ if(!course.requirements || course.requirements.length===0) return true; const map = {}; subjects.forEach(s=> map[s.subject.toLowerCase()]=s.symbol); for(const req of course.requirements){ const have = map[req.subject.toLowerCase()]; if(!have) return false; if(SYMBOL_VALUE[have] < SYMBOL_VALUE[req.minSymbol]) return false } return true }
  async function apply(instId,courseId){ if(!user) return alert('signin'); const appsToInst = applications.filter(a=>a.institutionId===instId); if(appsToInst.length>=2) return alert('max 2 applications per institution reached'); await applyToCourse({studentId:user.uid, institutionId:instId, courseId, transcriptUrl, transcriptData:subjects, status:'submitted', createdAt:new Date().toISOString()}); alert('applied'); const apps = await listStudentApplications(user.uid); setApplications(apps) }
  return (<><Nav/><div className='container'><div className='card'><h2>Student Dashboard</h2><p className='small'>Welcome {profile?.displayName}</p></div><div className='card'><h3>Upload Transcript (PDF)</h3><input type='file' accept='application/pdf' onChange={e=>setFile(e.target.files[0])}/><div style={{marginTop:8}}><button onClick={doUpload} className='btn'>Upload</button>{progress>0 && <span style={{marginLeft:8}}>Uploading {progress}%</span>}</div><div style={{marginTop:12}}><h4>Enter subjects & symbols</h4>{subjects.map((s,i)=>(<div key={i} style={{display:'flex',gap:8,marginTop:8}}><input value={s.subject} onChange={e=>updateSubject(i,'subject',e.target.value)} className='p-2 border'/><select value={s.symbol} onChange={e=>updateSubject(i,'symbol',e.target.value)} className='p-2 border'>{SYMBOLS.map(x=>(<option key={x} value={x}>{x}</option>))}</select></div>))}<div style={{marginTop:8}}><button onClick={addSubject} className='btn'>Add subject</button></div></div></div><div className='card'><h3>Courses filtered by your transcript</h3><label>Institution:</label><select value={selectedInstitution} onChange={e=>setSelectedInstitution(e.target.value)} className='p-2 border w-full mt-2'><option value=''>--select--</option>{institutions.map(i=>(<option key={i.id} value={i.id}>{i.name}</option>))}</select><div style={{marginTop:12}}>{courses.filter(matches).map(c=>(<div key={c.id} style={{display:'flex',justifyContent:'space-between',alignItems:'center',padding:8,border:'1px solid #e2e8f0',borderRadius:6,marginBottom:8}}><div><div style={{fontWeight:600}}>{c.title}</div><div style={{fontSize:12,color:'#475569'}}>{c.description}</div>{c.requirements && <div style={{fontSize:12,color:'#94a3b8'}}>Requires: {c.requirements.map(r=>r.subject+' ≥ '+r.minSymbol).join(', ')}</div>}</div><div><button onClick={()=>apply(selectedInstitution,c.id)} className='btn'>Apply</button></div></div>))}</div></div><div className='card'><h3>Your Applications</h3>{applications.length===0 && <div>No applications</div>}{applications.map(a=>(<div key={a.id} style={{padding:8,border:'1px solid #e2e8f0',borderRadius:6,marginTop:8}}><div><strong>Course:</strong> {a.courseId} — <strong>Status:</strong> {a.status}</div><div style={{fontSize:12,color:'#64748b'}}>Submitted: {a.createdAt}</div></div>))}</div></div></>) }
